// Catalogo normalizado
export const INVENTARIO_CATALOG = {
  "Abedules": [
    { proveedor: "Aseo", producto: "Aceite de Oliva", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Aceto Balsámico", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Ambientador", min_stock: 5, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas L", min_stock: 3, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas M", min_stock: 4, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas S", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "CIF", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Café Granulado", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Esponja", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Guantes", min_stock: 5, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Jabón de Mano", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Lavaloza", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Lustra Muebles", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Papel Interfoliado", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Paño Amarillo", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Paño Azul", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Paño Verde", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Poet", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Repuesto Mopa Avión", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Vinagre", min_stock: 3, categoria: "Aseo" },
    { proveedor: "Cafetería", producto: "Café Granulado", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Endulzante", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Leche Líquida", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Leche en Polvo", min_stock: 2, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Papel Higiénico", min_stock: 3, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Resma Papel Carta", min_stock: 1, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Servilletas", min_stock: 3, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Toalla de Papel", min_stock: 1, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Vainilla", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Corporate Coffee", producto: "Café Grano (KG)", min_stock: 1, categoria: "Cafetería", subcategoria: "Corporate Coffee" },
    { proveedor: "Café Caribe", producto: "Café Grano (KG)", min_stock: 1, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Café Caribe", producto: "Café Molido (KG)", min_stock: 1, categoria: "Cafetería", subcategoria: "Café Caribe" },
  ],
  "Alto el Golf": [
    { proveedor: "Aseo", producto: "Bolsas 50x70", min_stock: 8, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 70x90", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 80x110", min_stock: 4, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Esponja", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Cafetería", producto: "Endulzante", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Leche Líquida", min_stock: 4, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Papel Higiénico", min_stock: 7, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Resma Papel Carta", min_stock: 2, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Servilletas", min_stock: 2, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Toalla de Papel", min_stock: 3, categoria: "Papelería" },
    { proveedor: "Corporate Coffee", producto: "Café Grano (KG)", min_stock: 1, categoria: "Cafetería", subcategoria: "Corporate Coffee" },
    { proveedor: "Café Caribe", producto: "Café Grano (KG)", min_stock: 3, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Café Caribe", producto: "Café Molido (KG)", min_stock: 3, categoria: "Cafetería", subcategoria: "Café Caribe" },
  ],
  "Apoquindo": [
    { proveedor: "Aseo", producto: "Bolsas 50x70", min_stock: 6, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 70x90", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 80x110", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Esponja", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Cafetería", producto: "Café Granulado", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Endulzante", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Leche Líquida", min_stock: 5, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Papel Higiénico", min_stock: 5, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Resma Papel Carta", min_stock: 1, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Servilletas", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Toalla de Papel", min_stock: 2, categoria: "Papelería" },
    { proveedor: "Corporate Coffee", producto: "Café Grano (KG)", min_stock: 1, categoria: "Cafetería", subcategoria: "Corporate Coffee" },
    { proveedor: "Café Caribe", producto: "Café Grano (KG)", min_stock: 3, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Café Caribe", producto: "Café Molido (KG)", min_stock: 3, categoria: "Cafetería", subcategoria: "Café Caribe" },
  ],
  "Cerro el Plomo": [
    { proveedor: "Aseo", producto: "Ambientador", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Antigrasa", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Atomizador", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 50x70", min_stock: 11, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 70x90", min_stock: 7, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 80x110", min_stock: 5, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "CIF", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Esponja", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Jabón de Mano", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Lavaloza", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Lustra Muebles", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Cafetería", producto: "Aceite de Oliva", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Aceto Balsámico", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Café Caribe", producto: "Café Grano (KG)", min_stock: 3, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Café Caribe", producto: "Café Molido (KG)", min_stock: 3, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Cafetería", producto: "Endulzante", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Leche Líquida", min_stock: 4, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Limón", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Papel Higiénico", min_stock: 5, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Resma Papel Carta", min_stock: 1, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Sal", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Servilletas", min_stock: 5, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Toalla de Papel", min_stock: 2, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Té Lipton", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Té Negro", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Té Surtido", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Vinagre", min_stock: 2, categoria: "Cafetería" },
    { proveedor: "Corporate Coffee", producto: "Azúcar", min_stock: 1, categoria: "Cafetería", subcategoria: "Corporate Coffee" },
    { proveedor: "Corporate Coffee", producto: "Café Grano (KG)", min_stock: 2, categoria: "Cafetería", subcategoria: "Corporate Coffee" },
    { proveedor: "Corporate Coffee", producto: "Chocolate", min_stock: 4, categoria: "Cafetería", subcategoria: "Corporate Coffee" },
    { proveedor: "Corporate Coffee", producto: "Endulzante", min_stock: 1, categoria: "Cafetería", subcategoria: "Corporate Coffee" },
    { proveedor: "Corporate Coffee", producto: "Leche en Polvo", min_stock: 24, categoria: "Cafetería", subcategoria: "Corporate Coffee" },
    { proveedor: "Corporate Coffee", producto: "Revolvedores", min_stock: 3, categoria: "Cafetería", subcategoria: "Corporate Coffee" },
    { proveedor: "Corporate Coffee", producto: "Té", min_stock: 2, categoria: "Cafetería", subcategoria: "Corporate Coffee" },
    { proveedor: "Corporate Coffee", producto: "Vainilla", min_stock: 20, categoria: "Cafetería", subcategoria: "Corporate Coffee" },
  ],
  "Florida Center": [
    { proveedor: "Aseo", producto: "Ambientador", min_stock: 5, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 50x70", min_stock: 5, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 70x90", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 80x110", min_stock: 6, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "CIF", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Esponja", min_stock: 5, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Guantes", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Igenix", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Lavaloza", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Limpia Vidrios", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Lustra Muebles", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Mopa Avión", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Paño Amarillo", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Paño Azul", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Paño Esponja", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Paño Verde", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Cafetería", producto: "Aceite de Oliva", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Aceto Balsámico", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Azúcar", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Corporate Coffee", producto: "Café Grano (KG)", min_stock: 4, categoria: "Cafetería", subcategoria: "Corporate Coffee" },
    { proveedor: "Café Caribe", producto: "Café Grano (KG)", min_stock: 4, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Café Caribe", producto: "Café Molido (KG)", min_stock: 4, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Cafetería", producto: "Café Granulado", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Endulzante", min_stock: 2, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Leche Líquida", min_stock: 6, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Limón", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Papel Higiénico", min_stock: 1, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Revolvedores", min_stock: 3, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Servilletas", min_stock: 4, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Toalla de Papel", min_stock: 2, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Té Negro", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Té de Hierbas", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Vasos", min_stock: 63, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Vinagre", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Papelería", producto: "Resma Papel Carta", min_stock: 1, categoria: "Papelería" },
  ],
  "Isidora": [
    { proveedor: "Aseo", producto: "Bolsas 50x70", min_stock: 4, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 70x90", min_stock: 8, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 80x110", min_stock: 6, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Esponja", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Cafetería", producto: "Endulzante", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Leche Líquida", min_stock: 8, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Papel Higiénico", min_stock: 3, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Resma Papel Carta", min_stock: 2, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Servilletas", min_stock: 2, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Toalla de Papel", min_stock: 2, categoria: "Papelería" },
    { proveedor: "Corporate Coffee", producto: "Café Grano (KG)", min_stock: 1, categoria: "Cafetería", subcategoria: "Corporate Coffee" },
    { proveedor: "Café Caribe", producto: "Café Grano (KG)", min_stock: 10, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Café Caribe", producto: "Café Molido (KG)", min_stock: 10, categoria: "Cafetería", subcategoria: "Café Caribe" },
  ],
  "Kennedy": [
    { proveedor: "Aseo", producto: "Bolsas 50x70", min_stock: 4, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 70x90", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 80x110", min_stock: 4, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Esponja", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Cafetería", producto: "Endulzante", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Leche Líquida", min_stock: 3, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Papel Higiénico", min_stock: 10, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Papel Interfoliado", min_stock: 1, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Resma Papel Carta", min_stock: 1, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Servilletas", min_stock: 3, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Toalla de Papel", min_stock: 2, categoria: "Papelería" },
    { proveedor: "Corporate Coffee", producto: "Café Grano (KG)", min_stock: 1, categoria: "Cafetería", subcategoria: "Corporate Coffee" },
    { proveedor: "Café Caribe", producto: "Café Grano (KG)", min_stock: 4, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Café Caribe", producto: "Café Molido (KG)", min_stock: 4, categoria: "Cafetería", subcategoria: "Café Caribe" },
  ],
  "Los Militares - NACE": [
    { proveedor: "Aseo", producto: "Bolsas 50x70", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 70x90", min_stock: 3, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 80x110", min_stock: 3, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Esponja", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 3, categoria: "Aseo" },
    { proveedor: "Cafetería", producto: "Café Granulado", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Endulzante", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Leche Líquida", min_stock: 4, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Papel Higiénico", min_stock: 3, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Resma Papel Carta", min_stock: 4, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Servilletas", min_stock: 3, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Toalla de Papel", min_stock: 3, categoria: "Papelería" },
    { proveedor: "Corporate Coffee", producto: "Café Grano (KG)", min_stock: 1, categoria: "Cafetería", subcategoria: "Corporate Coffee" },
    { proveedor: "Café Caribe", producto: "Café Grano (KG)", min_stock: 1, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Café Caribe", producto: "Café Molido (KG)", min_stock: 1, categoria: "Cafetería", subcategoria: "Café Caribe" },
  ],
  "Manuel Montt": [
    { proveedor: "Aseo", producto: "Bolsas 50x70", min_stock: 14, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 70x90", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 80x110", min_stock: 3, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Esponja", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Corporate Coffee", producto: "Café Grano (KG)", min_stock: 16, categoria: "Cafetería", subcategoria: "Corporate Coffee" },
    { proveedor: "Café Caribe", producto: "Café Grano (KG)", min_stock: 16, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Café Caribe", producto: "Café Molido (KG)", min_stock: 16, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Cafetería", producto: "Endulzante", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Leche Líquida", min_stock: 2, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Papel Higiénico", min_stock: 3, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Resma Papel Carta", min_stock: 1, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Servilletas", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Toalla de Papel", min_stock: 2, categoria: "Papelería" },
  ],
  "Monjitas": [
    { proveedor: "Aseo", producto: "Bolsas 50x70", min_stock: 6, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 70x90", min_stock: 3, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 80x110", min_stock: 15, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "CIF", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Esponja", min_stock: 4, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Repuesto Jabón", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Cafetería", producto: "Aceite de Oliva", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Aceto Balsámico", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Café Granulado", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Endulzante", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Leche Líquida", min_stock: 5, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Limón", min_stock: 2, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Papel Higiénico", min_stock: 13, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Resma Papel Carta", min_stock: 1, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Sal", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Servilletas", min_stock: 5, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Toalla de Papel", min_stock: 3, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Té Lipton", min_stock: 2, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Té Negro", min_stock: 3, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Té de Hierbas", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Vinagre", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Corporate Coffee", producto: "Café Grano (KG)", min_stock: 1, categoria: "Cafetería", subcategoria: "Corporate Coffee" },
    { proveedor: "Café Caribe", producto: "Café Grano (KG)", min_stock: 3, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Café Caribe", producto: "Café Molido (KG)", min_stock: 3, categoria: "Cafetería", subcategoria: "Café Caribe" },
  ],
  "Neohaus": [
    { proveedor: "Aseo", producto: "Bolsas Basura", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Esponja", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Papel Interfoliado", min_stock: 7, categoria: "Aseo" },
    { proveedor: "Cafetería", producto: "Aceite de Oliva", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Café Granulado", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Endulzante", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Papel Higiénico", min_stock: 2, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Toalla de Papel", min_stock: 1, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Vasos", min_stock: 2, categoria: "Cafetería" },
    { proveedor: "Corporate Coffee", producto: "Café Grano (KG)", min_stock: 1, categoria: "Cafetería", subcategoria: "Corporate Coffee" },
    { proveedor: "Café Caribe", producto: "Café Grano (KG)", min_stock: 1, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Café Caribe", producto: "Café Molido (KG)", min_stock: 1, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Papelería", producto: "Resma Papel Carta", min_stock: 1, categoria: "Papelería" },
  ],
  "Nueva Las Condes": [
    { proveedor: "Aseo", producto: "Ambientador", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 50x70", min_stock: 6, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 70x90", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 80x110", min_stock: 3, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Esponja", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Mopa Rectangular", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Cafetería", producto: "Aceite de Oliva", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Café Granulado", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Endulzante", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Leche Líquida", min_stock: 4, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Papel Higiénico", min_stock: 11, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Resma Papel Carta", min_stock: 1, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Servilletas", min_stock: 4, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Toalla de Papel", min_stock: 4, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Té de Hierbas", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Corporate Coffee", producto: "Café Grano (KG)", min_stock: 1, categoria: "Cafetería", subcategoria: "Corporate Coffee" },
    { proveedor: "Café Caribe", producto: "Café Grano (KG)", min_stock: 3, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Café Caribe", producto: "Café Molido (KG)", min_stock: 3, categoria: "Cafetería", subcategoria: "Café Caribe" },
  ],
  "Plaza Egaña": [
    { proveedor: "Aseo", producto: "Bolsas 50x70", min_stock: 8, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 70x90", min_stock: 4, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 80x110", min_stock: 3, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Esponja", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Corporate Coffee", producto: "Café Grano (KG)", min_stock: 2, categoria: "Cafetería", subcategoria: "Corporate Coffee" },
    { proveedor: "Café Caribe", producto: "Café Grano (KG)", min_stock: 2, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Café Caribe", producto: "Café Molido (KG)", min_stock: 2, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Cafetería", producto: "Café Granulado", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Endulzante", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Leche Líquida", min_stock: 3, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Papel Higiénico", min_stock: 2, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Resma Papel Carta", min_stock: 2, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Servilletas", min_stock: 3, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Toalla de Papel", min_stock: 1, categoria: "Papelería" },
  ],
  "Santa Lucia": [
    { proveedor: "Aseo", producto: "Bolsas 50x70", min_stock: 3, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 70x90", min_stock: 3, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 80x110", min_stock: 3, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Esponja", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Cafetería", producto: "Azúcar", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Corporate Coffee", producto: "Café Grano (KG)", min_stock: 4, categoria: "Cafetería", subcategoria: "Corporate Coffee" },
    { proveedor: "Café Caribe", producto: "Café Grano (KG)", min_stock: 4, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Café Caribe", producto: "Café Molido (KG)", min_stock: 4, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Cafetería", producto: "Café Granulado", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Endulzante", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Leche Líquida", min_stock: 5, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Papel Higiénico", min_stock: 7, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Resma Papel Carta", min_stock: 2, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Servilletas", min_stock: 3, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Toalla de Papel", min_stock: 2, categoria: "Papelería" },
  ],
  "Santa Rosa": [
    { proveedor: "Aseo", producto: "Bolsas 50x70", min_stock: 3, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 70x90", min_stock: 5, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 80x110", min_stock: 7, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Esponja", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Papel Higiénico", min_stock: 12, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Toalla de Papel", min_stock: 3, categoria: "Aseo" },
    { proveedor: "Corporate Coffee", producto: "Café Grano (KG)", min_stock: 2, categoria: "Cafetería", subcategoria: "Corporate Coffee" },
    { proveedor: "Café Caribe", producto: "Café Grano (KG)", min_stock: 2, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Café Caribe", producto: "Café Molido (KG)", min_stock: 2, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Cafetería", producto: "Café Granulado", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Chocolate", min_stock: 2, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Endulzante", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Leche en Polvo", min_stock: 2, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Resma Papel Carta", min_stock: 2, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Servilletas", min_stock: 8, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Té de Hierbas", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Vainilla", min_stock: 2, categoria: "Cafetería" },
  ],
  "Suecia": [
    { proveedor: "Aseo", producto: "Bolsas 50x70", min_stock: 8, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 70x90", min_stock: 4, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 80x110", min_stock: 3, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Esponja", min_stock: 4, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Corporate Coffee", producto: "Café Grano (KG)", min_stock: 2, categoria: "Cafetería", subcategoria: "Corporate Coffee" },
    { proveedor: "Café Caribe", producto: "Café Grano (KG)", min_stock: 2, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Café Caribe", producto: "Café Molido (KG)", min_stock: 2, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Cafetería", producto: "Café Granulado", min_stock: 2, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Endulzante", min_stock: 2, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Leche Líquida", min_stock: 5, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Papel Higiénico", min_stock: 8, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Resma Papel Carta", min_stock: 1, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Toalla de Papel", min_stock: 4, categoria: "Papelería" },
  ],
  "Tobalaba-P3": [
    { proveedor: "Aseo", producto: "Bolsas Basura", min_stock: 12, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Esponja", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Cafetería", producto: "Azúcar", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Corporate Coffee", producto: "Café Grano (KG)", min_stock: 1, categoria: "Cafetería", subcategoria: "Corporate Coffee" },
    { proveedor: "Café Caribe", producto: "Café Grano (KG)", min_stock: 1, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Café Caribe", producto: "Café Molido (KG)", min_stock: 1, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Cafetería", producto: "Endulzante", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Leche Líquida", min_stock: 7, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Papel Higiénico", min_stock: 12, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Resma Papel Carta", min_stock: 1, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Servilletas", min_stock: 3, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Toalla de Papel", min_stock: 3, categoria: "Papelería" },
  ],
  "Vespucio": [
    { proveedor: "Aseo", producto: "Ambientador", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Antigrasa", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Antisarro", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 50x70", min_stock: 5, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 70x90", min_stock: 6, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Bolsas 80x110", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "CIF", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Esponja", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Guantes", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Jabón de Mano", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Lavaloza", min_stock: 3, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Limpia Vidrios", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Lisoform", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Lustra Muebles", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Mopa Avión", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Mopa Húmeda", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Papel Higiénico", min_stock: 11, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Paño Amarillo", min_stock: 3, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Paño Azul", min_stock: 5, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Paño Esponja", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Paño Verde", min_stock: 2, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Sal Lavavajillas", min_stock: 1, categoria: "Aseo" },
    { proveedor: "Aseo", producto: "Toalla de Papel", min_stock: 3, categoria: "Aseo" },
    { proveedor: "Cafetería", producto: "Aceite de Oliva", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Aceto Balsámico", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Azúcar", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Café Granulado", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Endulzante", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Leche Líquida", min_stock: 4, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Limón", min_stock: 2, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Resma Papel Carta", min_stock: 2, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Resma Papel Oficio", min_stock: 4, categoria: "Papelería" },
    { proveedor: "Cafetería", producto: "Revolvedores", min_stock: 4, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Sal", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Servilletas", min_stock: 3, categoria: "Cafetería" },
    { proveedor: "Cafetería", producto: "Vinagre", min_stock: 1, categoria: "Cafetería" },
    { proveedor: "Corporate Coffee", producto: "Café Grano (KG)", min_stock: 1, categoria: "Cafetería", subcategoria: "Corporate Coffee" },
    { proveedor: "Café Caribe", producto: "Café Grano (KG)", min_stock: 4, categoria: "Cafetería", subcategoria: "Café Caribe" },
    { proveedor: "Café Caribe", producto: "Café Molido (KG)", min_stock: 4, categoria: "Cafetería", subcategoria: "Café Caribe" },
  ],
  "Chery": [],
  "Coldwell": [],
  "Liquidos": [],
  "Londres 43 - PPD": [],
  "S2GO": [],
  "Salesforce": [],
};
export const INVENTARIO_SEDES = ["Abedules", "Alto el Golf", "Apoquindo", "Cerro el Plomo", "Chery", "Coldwell", "Florida Center", "Isidora", "Kennedy", "Liquidos", "Londres 43 - PPD", "Los Militares - NACE", "Manuel Montt", "Monjitas", "Neohaus", "Nueva Las Condes", "Plaza Egaña", "S2GO", "Salesforce", "Santa Lucia", "Santa Rosa", "Suecia", "Tobalaba-P3", "Vespucio"];