// Catalogo de productos por sede con stock minimo calculado del historico 2025
export const INVENTARIO_CATALOG = {
  "Abedules": [
    { proveedor: "Aseo", producto: "Aceite de oliva", min_stock: 2 },
    { proveedor: "Aseo", producto: "Aceto", min_stock: 1 },
    { proveedor: "Aseo", producto: "Aerosol de aroma", min_stock: 5 },
    { proveedor: "Aseo", producto: "Bolsas L", min_stock: 3 },
    { proveedor: "Aseo", producto: "Bolsas M", min_stock: 4 },
    { proveedor: "Aseo", producto: "Bolsas S", min_stock: 2 },
    { proveedor: "Aseo", producto: "Café instantaneao", min_stock: 1 },
    { proveedor: "Aseo", producto: "Cif en crema", min_stock: 2 },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 2 },
    { proveedor: "Aseo", producto: "Esponja 4U", min_stock: 1 },
    { proveedor: "Aseo", producto: "Guantes", min_stock: 5 },
    { proveedor: "Aseo", producto: "Jabón de mano", min_stock: 1 },
    { proveedor: "Aseo", producto: "Lavaloza", min_stock: 1 },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1 },
    { proveedor: "Aseo", producto: "Lustramueble", min_stock: 1 },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 2 },
    { proveedor: "Aseo", producto: "Papel interfoliado", min_stock: 1 },
    { proveedor: "Aseo", producto: "Paño Verde", min_stock: 1 },
    { proveedor: "Aseo", producto: "Paños Amarillo", min_stock: 1 },
    { proveedor: "Aseo", producto: "Paños Azul", min_stock: 1 },
    { proveedor: "Aseo", producto: "Poet", min_stock: 1 },
    { proveedor: "Aseo", producto: "Repuesto avion", min_stock: 1 },
    { proveedor: "Aseo", producto: "Vinagre", min_stock: 3 },
    { proveedor: "Cafeteria", producto: "Cafe Granulado", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Endulzante", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Leche en polvo", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Leche liquida", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Papel Higienico (UN)", min_stock: 3 },
    { proveedor: "Cafeteria", producto: "Resma Papel Fotocopia (UN)", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Servilletas", min_stock: 3 },
    { proveedor: "Cafeteria", producto: "Toalla de Papel Jumbo (UN)", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Vainilla", min_stock: 1 },
    { proveedor: "Coporate Coffe", producto: "Cafe Grano (KG)", min_stock: 1 },
  ],
  "Alto el Golf": [
    { proveedor: "Aseo", producto: "Bolsas Basura 50x70", min_stock: 8 },
    { proveedor: "Aseo", producto: "Bolsas Basura 70x90", min_stock: 1 },
    { proveedor: "Aseo", producto: "Bolsas Basura 80x110", min_stock: 4 },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1 },
    { proveedor: "Aseo", producto: "Esponja 4U", min_stock: 2 },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1 },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 1 },
    { proveedor: "Cafe Caribe", producto: "Cafe Grano (KG)", min_stock: 3 },
    { proveedor: "Cafeteria", producto: "Endulzante", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Leche liquida", min_stock: 4 },
    { proveedor: "Cafeteria", producto: "Papel Higienico (UN)", min_stock: 7 },
    { proveedor: "Cafeteria", producto: "Resma Papel Fotocopia (UN)", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Servilletas", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Toalla de Papel Jumbo (UN)", min_stock: 3 },
  ],
  "Apoquindo": [
    { proveedor: "Aseo", producto: "Bolsas Basura 50x70", min_stock: 6 },
    { proveedor: "Aseo", producto: "Bolsas Basura 70x90", min_stock: 2 },
    { proveedor: "Aseo", producto: "Bolsas Basura 80x110", min_stock: 2 },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1 },
    { proveedor: "Aseo", producto: "Esponja 4U", min_stock: 1 },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1 },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 1 },
    { proveedor: "Cafe Caribe", producto: "Cafe Grano (KG)", min_stock: 3 },
    { proveedor: "Cafeteria", producto: "Cafe Granulado", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Endulzante", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Leche liquida", min_stock: 5 },
    { proveedor: "Cafeteria", producto: "Papel Higienico (UN)", min_stock: 5 },
    { proveedor: "Cafeteria", producto: "Resma Papel Fotocopia (UN)", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Servilletas", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Toalla de Papel Jumbo (UN)", min_stock: 2 },
  ],
  "Cerro el Plomo": [
    { proveedor: "Aseo", producto: "Ambientador", min_stock: 1 },
    { proveedor: "Aseo", producto: "Atomizador Pistola", min_stock: 2 },
    { proveedor: "Aseo", producto: "Bolsas Basura 50x70", min_stock: 11 },
    { proveedor: "Aseo", producto: "Bolsas Basura 70x90", min_stock: 7 },
    { proveedor: "Aseo", producto: "Bolsas Basura 80x110", min_stock: 5 },
    { proveedor: "Aseo", producto: "Cif en crema", min_stock: 1 },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1 },
    { proveedor: "Aseo", producto: "Esponja 4U", min_stock: 2 },
    { proveedor: "Aseo", producto: "Jabon liquido", min_stock: 1 },
    { proveedor: "Aseo", producto: "Lavaloza", min_stock: 1 },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1 },
    { proveedor: "Aseo", producto: "Limpiador Antigrasa", min_stock: 1 },
    { proveedor: "Aseo", producto: "Lustra muebles", min_stock: 1 },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Aceite de oliva", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Aceto Balsamico", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Cafe Caribe Grano (KG)", min_stock: 3 },
    { proveedor: "Cafeteria", producto: "Endulzante", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Leche liquida", min_stock: 4 },
    { proveedor: "Cafeteria", producto: "Papel Higienico (UN)", min_stock: 5 },
    { proveedor: "Cafeteria", producto: "Resma Papel Fotocopia (UN)", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Sal", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Servilletas", min_stock: 5 },
    { proveedor: "Cafeteria", producto: "Sucedaneo Limon", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Te caja amarillo Lipton", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Te caja negro supremo", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Te caja surtidos", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Toalla de Papel Jumbo (UN)", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Vinagre", min_stock: 2 },
    { proveedor: "Corporate Coffe", producto: "Azucar (UN)", min_stock: 1 },
    { proveedor: "Corporate Coffe", producto: "Cafe Grano (KG)", min_stock: 2 },
    { proveedor: "Corporate Coffe", producto: "Chocolate (KG)", min_stock: 4 },
    { proveedor: "Corporate Coffe", producto: "Leche en polvo (KG)", min_stock: 24 },
    { proveedor: "Corporate Coffe", producto: "Removerdores (UN)", min_stock: 3 },
    { proveedor: "Corporate Coffe", producto: "Sucralosa (UN)", min_stock: 1 },
    { proveedor: "Corporate Coffe", producto: "Te (KG)", min_stock: 2 },
    { proveedor: "Corporate Coffe", producto: "Vainilla (KG)", min_stock: 20 },
  ],
  "Florida Center": [
    { proveedor: "Aseo", producto: "Bolsas Basura 50x70", min_stock: 5 },
    { proveedor: "Aseo", producto: "Bolsas Basura 70x90", min_stock: 2 },
    { proveedor: "Aseo", producto: "Bolsas Basura 80x110", min_stock: 6 },
    { proveedor: "Aseo", producto: "CIF", min_stock: 1 },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1 },
    { proveedor: "Aseo", producto: "Desodorante Ambiental", min_stock: 5 },
    { proveedor: "Aseo", producto: "Esponja 4U", min_stock: 5 },
    { proveedor: "Aseo", producto: "Guantes Multiuso", min_stock: 2 },
    { proveedor: "Aseo", producto: "Igenix", min_stock: 2 },
    { proveedor: "Aseo", producto: "Lavalozas", min_stock: 1 },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1 },
    { proveedor: "Aseo", producto: "Limpia vidrio", min_stock: 1 },
    { proveedor: "Aseo", producto: "Lustra Mueble", min_stock: 2 },
    { proveedor: "Aseo", producto: "Mopa Avión", min_stock: 1 },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 1 },
    { proveedor: "Aseo", producto: "Paño Esponja", min_stock: 1 },
    { proveedor: "Aseo", producto: "Paños Multiuso Amarillo", min_stock: 1 },
    { proveedor: "Aseo", producto: "Paños Multiuso Azul", min_stock: 2 },
    { proveedor: "Aseo", producto: "Paños Multiuso Verde", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Aceite de Oliva", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Aceto Balsámico", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Azucar", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Cafe Grano (KG)", min_stock: 4 },
    { proveedor: "Cafeteria", producto: "Café soluble", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Endulzante", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Ensencia de Limón", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Leche Liquida", min_stock: 6 },
    { proveedor: "Cafeteria", producto: "Papel Higienico (UN)", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Removedores", min_stock: 3 },
    { proveedor: "Cafeteria", producto: "Servilletas", min_stock: 4 },
    { proveedor: "Cafeteria", producto: "Supremo de Hierbas", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Toalla de Papel Jumbo (UN)", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Té Negro", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Té Premium", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Vasos Polipapel", min_stock: 63 },
    { proveedor: "Cafeteria", producto: "Vinagre", min_stock: 1 },
    { proveedor: "Papeleria", producto: "Resma Papel Fotocopia (UN)", min_stock: 1 },
  ],
  "Isidora": [
    { proveedor: "Aseo", producto: "Bolsas Basura 50x70", min_stock: 4 },
    { proveedor: "Aseo", producto: "Bolsas Basura 70x90", min_stock: 8 },
    { proveedor: "Aseo", producto: "Bolsas Basura 80x110", min_stock: 6 },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1 },
    { proveedor: "Aseo", producto: "Esponja 4U", min_stock: 2 },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1 },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 1 },
    { proveedor: "Cafe Caribe", producto: "Cafe Grano (KG)", min_stock: 10 },
    { proveedor: "Cafeteria", producto: "Endulzante", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Leche liquida", min_stock: 8 },
    { proveedor: "Cafeteria", producto: "Papel Higienico (UN)", min_stock: 3 },
    { proveedor: "Cafeteria", producto: "Resma Papel Fotocopia (UN)", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Servilletas", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Toalla de Papel Jumbo (UN)", min_stock: 2 },
  ],
  "Kennedy": [
    { proveedor: "Aseo", producto: "Bolsas Basura 50x70", min_stock: 4 },
    { proveedor: "Aseo", producto: "Bolsas Basura 70x90", min_stock: 1 },
    { proveedor: "Aseo", producto: "Bolsas Basura 80x110", min_stock: 4 },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1 },
    { proveedor: "Aseo", producto: "Esponja 4U", min_stock: 1 },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1 },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 2 },
    { proveedor: "Cafe Caribe", producto: "Cafe Grano (KG)", min_stock: 4 },
    { proveedor: "Cafeteria", producto: "Endulzante", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Leche liquida", min_stock: 3 },
    { proveedor: "Cafeteria", producto: "Papel Higienico (UN)", min_stock: 10 },
    { proveedor: "Cafeteria", producto: "Papel Interfoliado", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Resma Papel Fotocopia (UN)", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Servilletas", min_stock: 3 },
    { proveedor: "Cafeteria", producto: "Toalla de Papel Jumbo (UN)", min_stock: 2 },
  ],
  "Los Militares - NACE": [
    { proveedor: "Aseo", producto: "Bolsas Basura 50x70", min_stock: 2 },
    { proveedor: "Aseo", producto: "Bolsas Basura 70x90", min_stock: 3 },
    { proveedor: "Aseo", producto: "Bolsas Basura 80x110", min_stock: 3 },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1 },
    { proveedor: "Aseo", producto: "Esponja 4U", min_stock: 2 },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1 },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 3 },
    { proveedor: "Cafeteria", producto: "Cafe Granulado", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Endulzante", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Leche liquida", min_stock: 4 },
    { proveedor: "Cafeteria", producto: "Papel Higienico (UN)", min_stock: 3 },
    { proveedor: "Cafeteria", producto: "Resma Papel Fotocopia (UN)", min_stock: 4 },
    { proveedor: "Cafeteria", producto: "Servilletas", min_stock: 3 },
    { proveedor: "Cafeteria", producto: "Toalla de Papel Jumbo (UN)", min_stock: 3 },
    { proveedor: "Coporate Coffe", producto: "Cafe Grano (KG)", min_stock: 1 },
  ],
  "Manuel Montt": [
    { proveedor: "Aseo", producto: "Bolsas Basura  70x90", min_stock: 1 },
    { proveedor: "Aseo", producto: "Bolsas Basura  80x110", min_stock: 3 },
    { proveedor: "Aseo", producto: "Bolsas Basura 50x70", min_stock: 14 },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1 },
    { proveedor: "Aseo", producto: "Esponja 4U", min_stock: 2 },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1 },
    { proveedor: "Aseo", producto: "Limpia piso", min_stock: 1 },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Cafe Grano (KG)", min_stock: 16 },
    { proveedor: "Cafeteria", producto: "Endulzante", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Leche Liquida", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Leche Líquida", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Papel Higienico (UN)", min_stock: 3 },
    { proveedor: "Cafeteria", producto: "Resma Papel Fotocopia (UN)", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Servilleta", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Toalla de Papel Jumbo (UN)", min_stock: 2 },
  ],
  "Monjitas": [
    { proveedor: "Aseo", producto: "Bolsas Basura 50x70", min_stock: 6 },
    { proveedor: "Aseo", producto: "Bolsas Basura 70x90", min_stock: 3 },
    { proveedor: "Aseo", producto: "Bolsas Basura 80x110", min_stock: 15 },
    { proveedor: "Aseo", producto: "Cif en crema", min_stock: 1 },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 2 },
    { proveedor: "Aseo", producto: "Esponja 4U", min_stock: 4 },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 2 },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 1 },
    { proveedor: "Aseo", producto: "Repuesto Jabon", min_stock: 1 },
    { proveedor: "Cafe Caribe", producto: "Cafe Grano (KG)", min_stock: 3 },
    { proveedor: "Cafeteria", producto: "Aceite 500cc", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Aceto 500cc", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Cafe Granulado", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Endulzante", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Leche liquida", min_stock: 5 },
    { proveedor: "Cafeteria", producto: "Limon 1 Lt", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Papel Higienico (UN)", min_stock: 13 },
    { proveedor: "Cafeteria", producto: "Resma Papel Fotocopia (UN)", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Sal", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Servilletas", min_stock: 5 },
    { proveedor: "Cafeteria", producto: "Te Lypton (100 unid)", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Te Negro (100 unid)", min_stock: 3 },
    { proveedor: "Cafeteria", producto: "Te de hierbas (100 unid)", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Toalla de Papel Jumbo (UN)", min_stock: 3 },
    { proveedor: "Cafeteria", producto: "Vinagre 1 Lt", min_stock: 1 },
  ],
  "Neohaus": [
    { proveedor: "Aseo", producto: "Bolsas Basura", min_stock: 2 },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1 },
    { proveedor: "Aseo", producto: "Esponja 4U", min_stock: 1 },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1 },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 1 },
    { proveedor: "Aseo", producto: "Papel interfoliado", min_stock: 7 },
    { proveedor: "Cafeteria", producto: "Aceite de oliva", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Cafe Granulado", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Endulzante", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Papel Higienico (UN)", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Toalla de Papel Jumbo (UN)", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Vasos de cartón", min_stock: 2 },
    { proveedor: "Corporate Coffe", producto: "Cafe Grano (KG)", min_stock: 1 },
    { proveedor: "Papelería", producto: "Resma Papel Fotocopia (UN)", min_stock: 1 },
  ],
  "Nueva Las Condes": [
    { proveedor: "Aseo", producto: "Bolsas Basura 50x70", min_stock: 6 },
    { proveedor: "Aseo", producto: "Bolsas Basura 70x90", min_stock: 1 },
    { proveedor: "Aseo", producto: "Bolsas Basura 80x110", min_stock: 3 },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1 },
    { proveedor: "Aseo", producto: "Desodorante ambiental", min_stock: 1 },
    { proveedor: "Aseo", producto: "Esponja 4U", min_stock: 2 },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1 },
    { proveedor: "Aseo", producto: "Mopa Rectangular", min_stock: 1 },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 1 },
    { proveedor: "Cafe Caribe", producto: "Cafe Grano (KG)", min_stock: 3 },
    { proveedor: "Cafeteria", producto: "Aceite de oliva", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Cafe Granulado", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Endulzante", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Leche liquida", min_stock: 4 },
    { proveedor: "Cafeteria", producto: "Papel Higienico (UN)", min_stock: 11 },
    { proveedor: "Cafeteria", producto: "Resma Papel Fotocopia (UN)", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Servilletas", min_stock: 4 },
    { proveedor: "Cafeteria", producto: "Te de Hiervas surtida", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Toalla de Papel Jumbo (UN)", min_stock: 4 },
  ],
  "Plaza Egaña": [
    { proveedor: "Aseo", producto: "Bolsas Basura 50x70", min_stock: 8 },
    { proveedor: "Aseo", producto: "Bolsas Basura 70x90", min_stock: 4 },
    { proveedor: "Aseo", producto: "Bolsas Basura 80x110", min_stock: 3 },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1 },
    { proveedor: "Aseo", producto: "Esponja 4U", min_stock: 1 },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1 },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Cafe Grano (KG)", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Cafe Granulado", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Endulzante", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Leche Liquida", min_stock: 3 },
    { proveedor: "Cafeteria", producto: "Papel Higienico (UN)", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Resma Papel Fotocopia (UN)", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Servilletas", min_stock: 3 },
    { proveedor: "Cafeteria", producto: "Toalla de Papel Jumbo (UN)", min_stock: 1 },
  ],
  "Santa Lucia": [
    { proveedor: "Aseo", producto: "Bolsas Basura 50x70", min_stock: 3 },
    { proveedor: "Aseo", producto: "Bolsas Basura 70x90", min_stock: 3 },
    { proveedor: "Aseo", producto: "Bolsas Basura 80x110", min_stock: 3 },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1 },
    { proveedor: "Aseo", producto: "Esponja 4U", min_stock: 2 },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1 },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Azucar kg", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Cafe Grano (KG)", min_stock: 4 },
    { proveedor: "Cafeteria", producto: "Cafe Granulado", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Endulzante", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Leche Liquida", min_stock: 5 },
    { proveedor: "Cafeteria", producto: "Papel Higienico (UN)", min_stock: 7 },
    { proveedor: "Cafeteria", producto: "Resma Papel Fotocopia (UN)", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Servilletas", min_stock: 3 },
    { proveedor: "Cafeteria", producto: "Toalla de Papel Jumbo (UN)", min_stock: 2 },
  ],
  "Santa Rosa": [
    { proveedor: "Aseo", producto: "Bolsas Basura 50x70", min_stock: 3 },
    { proveedor: "Aseo", producto: "Bolsas Basura 70x90", min_stock: 5 },
    { proveedor: "Aseo", producto: "Bolsas Basura 80x110", min_stock: 7 },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1 },
    { proveedor: "Aseo", producto: "Esponja 4U", min_stock: 2 },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1 },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 2 },
    { proveedor: "Aseo", producto: "Papel Higienico (UN)", min_stock: 12 },
    { proveedor: "Aseo", producto: "Toalla de Papel Jumbo (UN)", min_stock: 3 },
    { proveedor: "Cafeteria", producto: "Cafe Grano (KG)", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Cafe Granulado", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Chocolate", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Endulzante", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Leche en polvo", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Resma Papel Fotocopia (UN)", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Servilletas", min_stock: 8 },
    { proveedor: "Cafeteria", producto: "Te Natural", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Vainilla 500gr", min_stock: 2 },
  ],
  "Suecia": [
    { proveedor: "Aseo", producto: "Bolsas Basura 50x70", min_stock: 8 },
    { proveedor: "Aseo", producto: "Bolsas Basura 70x90", min_stock: 4 },
    { proveedor: "Aseo", producto: "Bolsas Basura 80x110", min_stock: 3 },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1 },
    { proveedor: "Aseo", producto: "Esponja 4U", min_stock: 4 },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1 },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Cafe Grano (KG)", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Cafe Granulado", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Endulzante", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Leche Liquida", min_stock: 5 },
    { proveedor: "Cafeteria", producto: "Papel Higienico (UN)", min_stock: 8 },
    { proveedor: "Cafeteria", producto: "Resma Papel Fotocopia (UN)", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Toalla de Papel Jumbo (UN)", min_stock: 4 },
  ],
  "Tobalaba-P3": [
    { proveedor: "Aseo", producto: "Bolsas Basura", min_stock: 12 },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1 },
    { proveedor: "Aseo", producto: "Esponja 4U", min_stock: 1 },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1 },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Azucar (caja)", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Cafe Grano (KG)", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Endulzante", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Leche Liquida", min_stock: 7 },
    { proveedor: "Cafeteria", producto: "Papel Higienico (UN)", min_stock: 12 },
    { proveedor: "Cafeteria", producto: "Resma Papel Fotocopia (UN)", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Servilletas", min_stock: 3 },
    { proveedor: "Cafeteria", producto: "Toalla de Papel Jumbo (UN)", min_stock: 3 },
  ],
  "Vespucio": [
    { proveedor: "Aseo", producto: "Aerosol", min_stock: 2 },
    { proveedor: "Aseo", producto: "Antigrasa x 5L", min_stock: 1 },
    { proveedor: "Aseo", producto: "Antisarro x 5 L", min_stock: 1 },
    { proveedor: "Aseo", producto: "Bolsas Basura 50x70", min_stock: 5 },
    { proveedor: "Aseo", producto: "Bolsas Basura 70x90", min_stock: 6 },
    { proveedor: "Aseo", producto: "Bolsas Basura 80x110", min_stock: 2 },
    { proveedor: "Aseo", producto: "Cif en crema", min_stock: 1 },
    { proveedor: "Aseo", producto: "Cloro Gel", min_stock: 1 },
    { proveedor: "Aseo", producto: "Esponja 4U", min_stock: 1 },
    { proveedor: "Aseo", producto: "Guantes", min_stock: 2 },
    { proveedor: "Aseo", producto: "Jabon Lavaloza x 5L", min_stock: 1 },
    { proveedor: "Aseo", producto: "Jabon Liquido x 5L", min_stock: 1 },
    { proveedor: "Aseo", producto: "Lavavajillas", min_stock: 5 },
    { proveedor: "Aseo", producto: "Limpia Piso", min_stock: 1 },
    { proveedor: "Aseo", producto: "Limpia Vidrios", min_stock: 1 },
    { proveedor: "Aseo", producto: "Lisoform", min_stock: 1 },
    { proveedor: "Aseo", producto: "Lustra Muebles", min_stock: 2 },
    { proveedor: "Aseo", producto: "Mopa Avion", min_stock: 1 },
    { proveedor: "Aseo", producto: "Mopa Humeda", min_stock: 1 },
    { proveedor: "Aseo", producto: "Mopa Redonda", min_stock: 1 },
    { proveedor: "Aseo", producto: "Papel Higienico (UN)", min_stock: 11 },
    { proveedor: "Aseo", producto: "Paño Esponja x 6Uni.", min_stock: 2 },
    { proveedor: "Aseo", producto: "Sal Lavavajillas", min_stock: 1 },
    { proveedor: "Aseo", producto: "Toalla de Papel Jumbo (UN)", min_stock: 3 },
    { proveedor: "Aseo", producto: "Trapo Amarillo Uni.", min_stock: 3 },
    { proveedor: "Aseo", producto: "Trapo Azul Uni.", min_stock: 5 },
    { proveedor: "Aseo", producto: "Trapo Verde Uni.", min_stock: 2 },
    { proveedor: "Cafe Caribe", producto: "Cafe Grano (KG)", min_stock: 4 },
    { proveedor: "Cafeteria", producto: "Aceite de oliva", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Aceto Balsamico", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Cafe Granulado", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Endulzante", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Jugo de Limon", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Leche liquida", min_stock: 4 },
    { proveedor: "Cafeteria", producto: "Resma Papel Fot. Carta (UN)", min_stock: 2 },
    { proveedor: "Cafeteria", producto: "Resma Papel Fot. Oficio (UN)", min_stock: 4 },
    { proveedor: "Cafeteria", producto: "Revolvedores", min_stock: 4 },
    { proveedor: "Cafeteria", producto: "Sal", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Servilletas", min_stock: 3 },
    { proveedor: "Cafeteria", producto: "Sobre Azucar x Caja (800 S)", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Vinagre 1000 ml", min_stock: 1 },
    { proveedor: "Cafeteria", producto: "Vinagre 500 ml", min_stock: 1 },
  ],
};
export const INVENTARIO_SEDES = ["Abedules", "Alto el Golf", "Apoquindo", "Cerro el Plomo", "Florida Center", "Isidora", "Kennedy", "Los Militares - NACE", "Manuel Montt", "Monjitas", "Neohaus", "Nueva Las Condes", "Plaza Egaña", "Santa Lucia", "Santa Rosa", "Suecia", "Tobalaba-P3", "Vespucio"];